### ISSUE TITLE
txt64 is missing

### ISSUE THREAD

**Issue by stefanoverna** [imgix/imgix-url-params#12]
Any reason why [txt64](https://docs.imgix.com/apis/rendering/text/txt#using-base64-encoding) is not exposed?

**Comment by heyitsbryanm** [comment]
@stefanoverna, the `64` alias is available to _all_ imgix parameters (ex: https://bryansandbox.imgix.net/_static/images/img02.jpg?w64=MzAwCg), though it's most commonly used for parameters that are likely to use special characters in their values, such as [`blend`](https://docs.imgix.com/apis/rendering/blending), [`mark`](https://docs.imgix.com/apis/rendering/watermark) and [`txt`](https://docs.imgix.com/apis/rendering/text). You can read this in our documentation:
https://docs.imgix.com/apis/rendering#base64-variants

So, you can assume that a `64` variant exists for every imgix parameter.

**Comment by stefanoverna** [comment]
understood!
