### ISSUE TITLE
Format list of q parameter seems outdated

### ISSUE THREAD

**Issue by spand** [imgix/imgix-url-params#17]
**Describe the bug**
https://docs.imgix.com/apis/rendering/format/q says `Controls the output quality of lossy file formats (jpg, pjpg, webp, or jxr).`

yet `https://docs.imgix.com/apis/rendering/format/fm#avif` says `The AVIF file format supports lossy and lossless image formats.`

Is it outdated or does `q` simply not support controlling quality for avif format?

**Comment by luqven** [comment]
Hey @spand,

Thanks so much for opening this issue!

You _can_ use the ‘q’ parameter with AVIF.  We’ll be sure to update the docs to reflect this.

I’m going to go ahead and close this issue, but I’ll be sure to comment here when docs are updated.
