### ISSUE TITLE
"border-left",  "border-right",  "border-top",  "grid-colors",  "grid-size",  "pad-bottom",  "pad-left",  "pad-right",  "pad-top",  "transparency" are missing "available_in" key

### ISSUE THREAD

**Issue by stefanoverna** [imgix/imgix-url-params#8]
Every other parameter defines "available_in". Is this an error?

**Comment by heyitsbryanm** [comment]
@stefanoverna Looks like it.

Thanks for letting us know, we'll fix that soon.

**Comment by heyitsbryanm** [comment]
@stefanoverna are you currently using `available_in` for anything in your application? It seems that every imgix param should include `available_in` from my perspective.

**Comment by stefanoverna** [comment]
Yes, I was using it to know which are URL params! 

—
Stefano Verna

DatoCMS

--- original message ---
On September 23, 2020, 12:41 AM GMT+2 notifications@github.com wrote:



@stefanoverna are you currently using available_in for anything in your application? It seems that every imgix param should include available_in from my perspective.

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by heyitsbryanm** [comment]
@stefanoverna we just released a new version adding the missing `availabile_in:url` properties to [11.9.1](https://github.com/imgix/imgix-url-params/releases/tag/11.9.1).
 
Closing this issue.
